apiVersion : apps/v1
kind: Deployment
metadata:
  name: "madolkak8s-1ab6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "madolkak8s-1ab6"
  template:
    metadata:
      labels:
        app: "madolkak8s-1ab6"
    spec:
      containers:
        - name: "madolkak8s-1ab6"
          image: "madolkaazpy.azurecr.io/madolkak8s"
          ports:
          - containerPort: 80