apiVersion: v1
kind: Service
metadata:
    name: "madolkak8s-6828"
    labels:
        app: "madolkak8s-6828"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "madolkak8s-6828"