on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: madolkaazpy.azurecr.io
        username: ${{ secrets.acr_madolkaazpy_username }}
        password: ${{ secrets.acr_madolkaazpy_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t madolkaazpy.azurecr.io/madolkak8s:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push madolkaazpy.azurecr.io/madolkak8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_madolkak8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep madolka-k8sa801 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace madolka-k8sa801`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: madolka-k8sa801
        container-registry-url: madolkaazpy.azurecr.io
        container-registry-username: ${{ secrets.acr_madolkaazpy_username }}
        container-registry-password: ${{ secrets.acr_madolkaazpy_password }}
        secret-name: madolkak8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: madolka-k8sa801
        manifests: |
          manifests/deployment-5.yml
          manifests/service-5.yml
        images: |
          madolkaazpy.azurecr.io/madolkak8s:${{ github.sha }}
        imagepullsecrets: |
          madolkak8sdockerauth
